CREATE TABLE [dbo].[StructuredContent_Topics] (
    [Language]                   NVARCHAR (5)  NOT NULL,
    [ContentType]                NVARCHAR (50) NULL,
    [Title]                      NVARCHAR (700) NULL,
    [HWID]                       NVARCHAR (10)  NOT NULL,
    [ContentId]                  NVARCHAR (40) NULL,
    [AspectId]                   NVARCHAR (50) NULL,
    [AspectLabel]                NVARCHAR (50) NULL,
    [ConceptId]                  NVARCHAR (50) NULL,
    [ConceptLabel]               NVARCHAR (100) NULL,
    [ConceptAlternativeLabels]   NVARCHAR (max) NULL,
    [TopConceptId]               NVARCHAR (50) NULL,
    [TopConceptLabel]            NVARCHAR (100) NULL,
    [AspectId_2]                 NVARCHAR (50) NULL,
    [AspectLabel_2]              NVARCHAR (50) NULL,
    [ConceptId_2]                NVARCHAR (50) NULL,
    [ConceptLabel_2]             NVARCHAR (100) NULL,
    [ConceptAlternativeLabels_2] NVARCHAR (max) NULL,
    [TopConceptId_2]             NVARCHAR (50) NULL,
    [TopConceptLabel_2]          NVARCHAR (100) NULL,
    [FHWVISIBILITY]              NVARCHAR (50) NULL,
    [FHWCERTIFICATIONDATE]       DATE            NULL,
    [FHWLASTREVIEWEDDATE]        DATE            NULL,
    [FHWNEXTMEDICALREVIEWDATE]   DATE            NULL,
    [FHWLASTMEDICALREVIEWDATE]   DATE            NULL,
    [FHWPRIMARYMEDICALREVIEWER]  NVARCHAR (max) NULL,
    [FSTATUS]                    NVARCHAR (10) NULL,
    [FAUTHOR]                    NVARCHAR (50) NULL,
    [VERSION]                    NVARCHAR (10) NULL,
    [FHWREADINGLEVELN]           NVARCHAR (10) NULL,
    [FHWAUDIENCE]                NVARCHAR (50) NULL,
    [FHWCONTENTAREA]             NVARCHAR (50) NULL,
    [FMODULETYPE]                NVARCHAR (100) NULL,
    [DetailLevel]                NVARCHAR (50) NULL,
    [Taxonomy]                   NVARCHAR (1000) NULL,
    CONSTRAINT [PK_StructuredContent_Topics] PRIMARY KEY CLUSTERED ([HWID] ASC, [Language] ASC)
);

