CREATE TABLE [dbo].[StructuredContent_Topics] (
    [Language]                   NVARCHAR (100)  NOT NULL,
    [ContentType]                NVARCHAR (4000) NULL,
    [Title]                      NVARCHAR (4000) NULL,
    [HWID]                       NVARCHAR (100)  NOT NULL,
    [ContentId]                  NVARCHAR (4000) NULL,
    [AspectId]                   NVARCHAR (4000) NULL,
    [AspectLabel]                NVARCHAR (4000) NULL,
    [ConceptId]                  NVARCHAR (4000) NULL,
    [ConceptLabel]               NVARCHAR (4000) NULL,
    [ConceptAlternativeLabels]   NVARCHAR (4000) NULL,
    [TopConceptId]               NVARCHAR (4000) NULL,
    [TopConceptLabel]            NVARCHAR (4000) NULL,
    [AspectId_2]                 NVARCHAR (4000) NULL,
    [AspectLabel_2]              NVARCHAR (4000) NULL,
    [ConceptId_2]                NVARCHAR (4000) NULL,
    [ConceptLabel_2]             NVARCHAR (4000) NULL,
    [ConceptAlternativeLabels_2] NVARCHAR (4000) NULL,
    [TopConceptId_2]             NVARCHAR (4000) NULL,
    [TopConceptLabel_2]          NVARCHAR (4000) NULL,
    [FHWVISIBILITY]              NVARCHAR (4000) NULL,
    [FHWCERTIFICATIONDATE]       DATE            NULL,
    [FHWLASTREVIEWEDDATE]        DATE            NULL,
    [FHWNEXTMEDICALREVIEWDATE]   DATE            NULL,
    [FHWLASTMEDICALREVIEWDATE]   DATE            NULL,
    [FHWPRIMARYMEDICALREVIEWER]  NVARCHAR (4000) NULL,
    [FSTATUS]                    NVARCHAR (4000) NULL,
    [FAUTHOR]                    NVARCHAR (4000) NULL,
    [VERSION]                    NVARCHAR (4000) NULL,
    [FHWREADINGLEVELN]           NVARCHAR (4000) NULL,
    [FHWAUDIENCE]                NVARCHAR (4000) NULL,
    [FHWCONTENTAREA]             NVARCHAR (4000) NULL,
    [FMODULETYPE]                NVARCHAR (4000) NULL,
    [DetailLevel]                NVARCHAR (4000) NULL,
    [Taxonomy]                   NVARCHAR (4000) NULL,
    CONSTRAINT [PK_StructuredContent_Topics] PRIMARY KEY CLUSTERED ([HWID] ASC, [Language] ASC)
);

