

CREATE VIEW [dbo].[vwStructuredContent_Topics] AS (
SELECT [HWID]
      ,[ContentId]
	  ,[Title]
	  ,[Language]
      ,[ContentType]
      ,[AspectId]
	  ,[AspectLabel]
	  ,[ConceptId]
	  ,[ConceptLabel]
	  ,[ConceptAlternativeLabels]
	  ,[TopConceptId]
	  ,[TopConceptLabel]
	  ,[AspectId_2]
	  ,[AspectLabel_2]
	  ,[ConceptId_2]
	  ,[ConceptLabel_2]
	  ,[ConceptAlternativeLabels_2]
	  ,[TopConceptId_2]
	  ,[TopConceptLabel_2]
      ,[FMODULETYPE]
      ,[DetailLevel]
      ,[FHWVISIBILITY]
      ,[FHWCONTENTAREA]
      ,[FHWAUDIENCE]
      ,[FHWREADINGLEVELN]
      ,[VERSION]
      ,[FAUTHOR]
      ,[FSTATUS]
      ,[FHWPRIMARYMEDICALREVIEWER]
      ,[FHWLASTMEDICALREVIEWDATE]
      ,[FHWNEXTMEDICALREVIEWDATE]
      ,[FHWLASTREVIEWEDDATE]
      ,[FHWCERTIFICATIONDATE]
  FROM [dbo].[StructuredContent_Topics]
  )