




CREATE VIEW [dbo].[vwStructuredContent_Articles] AS (
SELECT [Hwid]
	  ,[TitleEnUs]
	  ,[TitleEnCa]
	  ,[TitleEsUs]
	  ,[AbstractEnUs]
	  ,[AbstractEnCa]
	  ,[AbstractEsUs]
	  ,[SectionsEnUs]
	  ,[SectionsEnCa]
	  ,[SectionsEsUs]
	  ,[facetidCondition]
      ,[facetConditions]
	  ,[Gender]
      ,[Age]
      ,[DeliverySetting]
      ,[Audiences]
      ,[Specialities]
      ,[ConceptsR1]
      ,[Concept]
      ,[CuratedEnCa]
      ,[SnomedCtR1]
      ,[Codewords]
      ,[facetidCategory]
      ,[categoryIds]
      ,[categories]
      ,[Languages]
      ,[Localizations]
      ,[KeywordsR1EsUs]
      ,[KeywordsR1EnUs]
      ,[ContentConfigurations]
      ,[Family]
      ,[EmrMaxAge]
      ,[EmrMinAge]
      ,[MaxAge]
      ,[MinAge]
      ,[ReleaseDate]
      ,[AuthoringVersion]
      ,[Version]
      ,[Type]
      ,[Rank]
      ,[IsSearchable]
      ,[AbstractIsAuthored]
  FROM [dbo].[StructuredContent_Articles]
  )