CREATE TABLE [dbo].[StructuredContent_Articles](
	[facetidCondition] [nvarchar](4000) NULL,
	[facetConditions] [nvarchar](4000) NULL,
	[DeliverySetting] [nvarchar](4000) NULL,
	[Audiences] [nvarchar](4000) NULL,
	[Specialities] [nvarchar](4000) NULL,
	[ConceptsR1] [nvarchar](4000) NULL,
	[Concept] [nvarchar](4000) NULL,
	[CuratedEnCa] [nvarchar](4000) NULL,
	[SnomedCtR1] [nvarchar](max) NULL,
	[Gender] [nvarchar](4000) NULL,
	[SectionsEsUs] [nvarchar](4000) NULL,
	[SectionsEnCa] [nvarchar](4000) NULL,
	[SectionsEnUs] [nvarchar](4000) NULL,
	[Age] [nvarchar](4000) NULL,
	[Codewords] [nvarchar](4000) NULL,
	[facetidCategory] [nvarchar](4000) NULL,
	[categoryIds] [nvarchar](4000) NULL,
	[categories] [nvarchar](4000) NULL,
	[Languages] [nvarchar](4000) NULL,
	[Localizations] [nvarchar](4000) NULL,
	[KeywordsR1EsUs] [nvarchar](max) NULL,
	[KeywordsR1EnUs] [nvarchar](max) NULL,
	[ContentConfigurations] [nvarchar](4000) NULL,
	[Family] [nvarchar](4000) NULL,
	[EmrMaxAge] [nvarchar](4000) NULL,
	[EmrMinAge] [nvarchar](4000) NULL,
	[MaxAge] [nvarchar](4000) NULL,
	[MinAge] [nvarchar](4000) NULL,
	[ReleaseDate] [nvarchar](4000) NULL,
	[AuthoringVersion] [nvarchar](4000) NULL,
	[Version] [nvarchar](4000) NULL,
	[Type] [nvarchar](4000) NULL,
	[Rank] [nvarchar](4000) NULL,
	[IsSearchable] [nvarchar](4000) NULL,
	[AbstractIsAuthored] [nvarchar](4000) NULL,
	[AbstractEsUs] [nvarchar](4000) NULL,
	[AbstractEnUs] [nvarchar](4000) NULL,
	[AbstractEnCa] [nvarchar](4000) NULL,
	[TitleEnCa] [nvarchar](4000) NULL,
	[TitleEsUs] [nvarchar](4000) NULL,
	[TitleEnUs] [nvarchar](4000) NULL,
	[Hwid] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_StructuredContent_Articles] PRIMARY KEY CLUSTERED ([Hwid] ASC) 
 ); 
 GO