CREATE TABLE [dbo].[StructuredContent_Topics](
	[Language] [nvarchar](100) NOT NULL,
	[ContentType] [nvarchar](4000) NULL,
	[Title] [nvarchar](4000) NULL,
	[HWID] [nvarchar](100) NOT NULL,
	[ContentId] [nvarchar](4000) NULL,
	[AspectId] [nvarchar](4000) NULL,
	[AspectLabel] [nvarchar](4000) NULL,
	[ConceptId] [nvarchar](4000) NULL,
	[ConceptLabel] [nvarchar](4000) NULL,
	[ConceptAlternativeLabels] [nvarchar](4000) NULL,
	[TopConceptId] [nvarchar](4000) NULL,
	[TopConceptLabel] [nvarchar](4000) NULL,
	[AspectId_2] [nvarchar](4000) NULL,
	[AspectLabel_2] [nvarchar](4000) NULL,
	[ConceptId_2] [nvarchar](4000) NULL,
	[ConceptLabel_2] [nvarchar](4000) NULL,
	[ConceptAlternativeLabels_2] [nvarchar](4000) NULL,
	[TopConceptId_2] [nvarchar](4000) NULL,
	[TopConceptLabel_2] [nvarchar](4000) NULL,
	[FHWVISIBILITY] [nvarchar](4000) NULL,
	[FHWCERTIFICATIONDATE] [date] NULL,
	[FHWLASTREVIEWEDDATE] [date] NULL,
	[FHWNEXTMEDICALREVIEWDATE] [date] NULL,
	[FHWLASTMEDICALREVIEWDATE] [date] NULL,
	[FHWPRIMARYMEDICALREVIEWER] [nvarchar](4000) NULL,
	[FSTATUS] [nvarchar](4000) NULL,
	[FAUTHOR] [nvarchar](4000) NULL,
	[VERSION] [nvarchar](4000) NULL,
	[FHWREADINGLEVELN] [nvarchar](4000) NULL,
	[FHWAUDIENCE] [nvarchar](4000) NULL,
	[FHWCONTENTAREA] [nvarchar](4000) NULL,
	[FMODULETYPE] [nvarchar](4000) NULL,
	[DetailLevel] [nvarchar](4000) NULL,
	[Taxonomy] [nvarchar](4000) NULL,
 CONSTRAINT [PK_StructuredContent_Topics] PRIMARY KEY CLUSTERED ([HWID] ASC, [Language] ASC)
 );
 GO