CREATE VIEW [Stg].[vwStructuredContent_Articles] AS (

SELECT 
 case when [facetidCondition] = 'NULL' then NULL else [facetidCondition] end as [facetidCondition]
,case when [facetConditions] = 'NULL' then NULL else [facetConditions] end as [facetConditions]
,case when [DeliverySetting] = 'NULL' then NULL else [DeliverySetting] end as [DeliverySetting]
,case when [Audiences] = 'NULL' then NULL else [Audiences] end as [Audiences]
,case when [Specialities] = 'NULL' then NULL else [Specialities] end as [Specialities]
,case when [ConceptsR1] = 'NULL' then NULL else [ConceptsR1] end as [ConceptsR1]
,case when [Concept] = 'NULL' then NULL else [Concept] end as [Concept]
,case when [CuratedEnCa] = 'NULL' then NULL else [CuratedEnCa] end as [CuratedEnCa]
,case when [SnomedCtR1] = 'NULL' then NULL else [SnomedCtR1] end as [SnomedCtR1]
,case when [Gender] = 'NULL' then NULL else [Gender] end as [Gender]
,case when [SectionsEsUs] = 'NULL' then NULL else [SectionsEsUs] end as [SectionsEsUs]
,case when [SectionsEnCa] = 'NULL' then NULL else [SectionsEnCa] end as [SectionsEnCa]
,case when [SectionsEnUs] = 'NULL' then NULL else [SectionsEnUs] end as [SectionsEnUs]
,case when [Age] = 'NULL' then NULL else [Age] end as [Age]
,case when [Codewords] = 'NULL' then NULL else [Codewords] end as [Codewords]
,case when [facetidCategory] = 'NULL' then NULL else [facetidCategory] end as [facetidCategory]
,case when [categoryIds] = 'NULL' then NULL else [categoryIds] end as [categoryIds]
,case when [categories] = 'NULL' then NULL else [categories] end as [categories]
,case when [Languages] = 'NULL' then NULL else [Languages] end as [Languages]
,case when [Localizations] = 'NULL' then NULL else [Localizations] end as [Localizations]
,case when [KeywordsR1EsUs] = 'NULL' then NULL else [KeywordsR1EsUs] end as [KeywordsR1EsUs]
,case when [KeywordsR1EnUs] = 'NULL' then NULL else [KeywordsR1EnUs] end as [KeywordsR1EnUs]
,case when [ContentConfigurations] = 'NULL' then NULL else [ContentConfigurations] end as [ContentConfigurations]
,[Family]
,[EmrMaxAge]
,[EmrMinAge]
,[MaxAge]
,[MinAge]
,[ReleaseDate]
,[AuthoringVersion]
,[Version]
,[Type]
,[Rank]
,[IsSearchable]
,[AbstractIsAuthored]
,[AbstractEsUs]
,[AbstractEnUs]
,[AbstractEnCa]
,[TitleEnCa]
,[TitleEsUs]
,[TitleEnUs]
,[Hwid]
FROM [Stg].[StructuredContent_document]
)